### ISSUE TITLE
Announce rpicamsrc moved to gst-plugins-good

### ISSUE THREAD

**Issue by tp-m** [thaytan/gst-rpicamsrc#100]
`rpicamsrc` is now in [gst-plugins-good](https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/) and will be included in the upcoming 1.17.90 release / upcoming 1.18 stable branch.

Should somehow announce this in the repo, and figure out what to do with open issues/PRs.

**Comment by PanderMusubi** [comment]
Like other users/contributors, I also missed this. Perhaps under all open issues, you can post that they need to be reported new at https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues and will be actively closed here.
