### ISSUE TITLE
Does it support USB cameras?

### ISSUE THREAD

**Issue by zanazakaryaie** [thaytan/gst-rpicamsrc#104]
Hi. I have used gst-rpicamsrc for CSI camera. It works well. Is there any option to use it for USB webcams? I mean Full-HD streaming with GPU hardware encoding and low CPU usage. If it is possible, could you please provide a sample command?

**Comment by thaytan** [comment]
No, rpicamsrc is specifically for doing the CSI->GPU encoder fast path. For USB cameras, you can use the omx encoder only older RPi, or try the v4l2 encoder driver on RPi4.
