### ISSUE TITLE
Its been ages, fired up my pi and tried to stream and got this...

### ISSUE THREAD

**Issue by DJMOJO** [thaytan/gst-rpicamsrc#110]
Youll have to excuse me guys, its been ages since I touched this but I got an itch to stream today and could not get my pi to stream.

> gst-launch-1.0 rpicamsrc bitrate=2000000 do-timestamp=true ! video/x-h264,width=1280,height=720,framerate=30/1,profile=high ! h264parse ! queue ! flvmux name=mux alsasrc device=plughw:1,0 ! audio/x-raw,rate=44100,channels=2 ! queue! voaacenc ! queue ! aacparse ! queue ! mux. mux. ! rtmpsink location=***rtmpsinfofromfacebookgoeshere***
> 
> 1] 1858
> [2] 1859
> [3] 1860
> [4] 1861
> [5] 1862
> [2]   Done                    s_ps=1
> [3]   Done                    s_psm=1
> pi@Chew:~ $ Setting pipeline to PAUSED ...
> ERROR: Pipeline doesn't want to pause.
> ERROR: from element /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0: Could not open audio device for recording.
> Additional debug info:
> gstalsasrc.c(741): gst_alsasrc_open (): /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0:
> Recording open error on device 'plughw:1,0': No such file or directory
> Setting pipeline to NULL ...
> Freeing pipeline ...

I made sure to update both the OS, all the packages and the rpi itself before trying any of this. I have a Behringer UCA202 usb audio interface to capture audio from and never had issues with it. Hope that helps so that I can get this setup working again.

Cheers

**Comment by thaytan** [comment]
`ERROR: from element /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0: Could not open audio device for recording.`

This error is from ALSA, nothing to do with rpicamsrc.
