### ISSUE TITLE
AWB settings are ignored

### ISSUE THREAD

**Issue by shrx** [thaytan/gst-rpicamsrc#26]
Setting `awb-mode` does not have any effect on the image, also setting `awb-mode=off` and manually `awb-gain-blue=4.2 awb-gain-red=1.0` doesn't have any effect, the image is always slightly too red.

**Comment by shrx** [comment]
Ok, this is only an issue if I also set `preview=false`. Why is that?

**Comment by shrx** [comment]
Could it be related to this discrepancy in the documentation? `awb-mode` is set to `off` (lowercase), but documentation says
> `awb-gain-blue       : Manual AWB Gain for blue channel when awb-mode=OFF` (uppercase)

**Comment by thaytan** [comment]
I updated the doc strings (thanks!), but I'm not sure why the properties wouldn't have an effect when awb-mode=off, or why changing the preview would make a difference. I'll try and remember to test when I'm physically in front of my rpi

**Comment by towolf** [comment]
Sounds like [this is the bug in question](https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=110273&p=758229&hilit=awb)?

**Comment by shrx** [comment]
Yep, looks like it is.

**Comment by thaytan** [comment]
There was a silly bug in my code setting the causing both awb-red and awb-blue to affect only the red channel. It's fixed by the commit above, so things might work better now.

**Comment by shrx** [comment]
Great, nice to see this fixed. I don't have the time to test it, but will reopen if anyone still has an issue with this.
