### ISSUE TITLE
could not find component 'vc.ril.camera'

### ISSUE THREAD

**Issue by mrtig** [thaytan/gst-rpicamsrc#28]
I just compiled *rpicamsrc* on RPi B+ running Arch and I get the following error when I try to use the *rpicamsrc* element in a gstreamer pipeline:
>mmal: mmal_component_create_core: could not find component 'vc.ril.camera'

Pipelines using *raspivid* are working perfectly with my setup.

**Comment by thaytan** [comment]
That's a new one! The only other people on the net that seem to have that problem don't have the camera enabled in the firmware config, but then raspivid shouldn't work either.

**Comment by philn** [comment]
I updated my branch this morning and now I'm getting the same error.

**Comment by thaytan** [comment]
Oops. Fix coming in a sec.
