### ISSUE TITLE
custom text and time stamp together as an annotation?

### ISSUE THREAD

**Issue by chetanbnaik** [thaytan/gst-rpicamsrc#45]
hi, is it possible to overlay a text that contains both custom text and time stamp together?

**Comment by thaytan** [comment]
The annotation-mode property is a bitmask. You can set any of custom-text (0x1) and date (0x4) and/or time (0x8) simultaneously by or'ing the values, or setting a string like 'annotation-mode=custom-text+date+time'

The actual custom text is set in the annotation-text property.

**Comment by chetanbnaik** [comment]
thanks for the answer, it works perfectly when using command line..
however, I am doing these things through python.
if I put rpisrc.set_property("annotation-mode","custom-text+date+time"), it fails to recognize. Any solution?

**Comment by chetanbnaik** [comment]
thanks a lot. I am using gstreamer through python. so the following works:
rpisrc.set_property("annotation-mode",0x1 + 0x4 + 0x8)
