### ISSUE TITLE
Implementing video/x-raw support?

### ISSUE THREAD

**Issue by bensch128** [thaytan/gst-rpicamsrc#48]
Hi, 
   I'm a noob to the rpi + gstreamer and I had some questions:
Is there amy plan to implement video/x-raw cap support in rpicamsrc?
I'm building a project where I need to extract several ROIs (up to 12 or so) from a single frame.
Since video/x-raw is needed, in your opinion, does it really matter performance-wise if v4l2src or rpicamsrc is used?

Thank you,
Ben

**Comment by thaytan** [comment]
It's possible, but not on my timetable. I want to merge JPEG format support first, at least.

**Comment by thaytan** [comment]
I just pushed support for raw video and JPEG capture, selected through caps negotiation:

gst-launch-1.0 rpicamsrc ! video/x-raw,format=RGB,width=640,height=480 ! fakesink.

**Comment by bensch128** [comment]
Nice job, thanks for that. I'm sure someone will find this patch useful.

Sincerely
Ben
