### ISSUE TITLE
failing launch command

### ISSUE THREAD

**Issue by tarballz** [thaytan/gst-rpicamsrc#5]
Hello all, so I've been working my way through this project and I feel like I'm so close to getting this to work!  I've followed all the instructions so far but when i run:
gst-launch-1.0 rpicamsrc bitrate=1000000 ! filesink location=test.h264

I get:
Setting pipeline to PAUSED ...
In src_start()
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: raspi_capture_setup: Failed to create camera component
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...

(all run as root, to avoid typing sudo constantly)
Thanks for any input on something I may have missed!

Info: This is running on Raspbian and I'm currently SSHing into the Pi.

**Comment by thaytan** [comment]
I assume you sorted this out or found another way by now. Please reopen if you still need some help.
