### ISSUE TITLE
Capturing in 1280x720 doesn't use the entire FoV

### ISSUE THREAD

**Issue by DavidVentura** [thaytan/gst-rpicamsrc#61]
Hi. I've just switched from recording at ~500x500 to 1280x720 and cropping but it seems like it's not using the entire FoV as it should, it's stated in the documentation.

Is this known? Is there a workaround?

**Comment by thaytan** [comment]
You can try setting the sensor-mode manually rpicamsrc sensor-mode=5

**Comment by nopmop** [comment]
https://github.com/thaytan/gst-rpicamsrc/issues/82#issuecomment-462890335

**Comment by PanderMusubi** [comment]
Can this issue be close?
