### ISSUE TITLE
Issue in building webrtc-unidirectional example

### ISSUE THREAD

**Issue by jagadishkamathk** [thaytan/gst-rpicamsrc#84]
I'm trying to build the webrtc-unidirectional-h264.c and I see it isn;t enabled by default. Configure excludes it with checking for GST_WEBRTC_EXAMPLE... no
WHat is the way to enable this in autogen or configure?

**Comment by thaytan** [comment]
and a new enough GStreamer 1.14 with WebRTC support

**Comment by jagadishkamathk** [comment]
Thank you. That seems to work. Just curious. How does the GST_WEBRTC_EXAMPLE environment variable gets set when these two packages get installed?

Also, webrtc exchange seems to happen but no media is seen on either chrome or firefox. That could be an entirely different issue though

**Comment by kevkid** [comment]
@jagadishkamathk I am seeing the same issue, Cant seem to get media to display. Maybe chrome, or firefox changes something? I have had much difficulty getting h264 to render in the webpage.

**Comment by jagadishkamathk** [comment]
But where you able to see the Raspi camera output on your browser?

**Comment by thaytan** [comment]
The camera doesn't turn on until you connect with a client and the streaming starts. It's a on my wish-list to extend the example with capabilities like record to disk and multiple client support (atm the 2nd client will fail because it tries to open the camera a 2nd time)

**Comment by kevkid** [comment]
I get this issue every time I try to compile the webrtc-unidirectional example.

```
make[2]: Entering directory '/home/pi/gst-rpicamsrc/examples'
  CCLD     webrtc-unidirectional-h264
libtool:   error: cannot find the library '/opt/gstreamer/lib/lib-pthread.la' or unhandled argument '/opt/gstreamer/lib/lib-pthread.la'
Makefile:397: recipe for target 'webrtc-unidirectional-h264' failed
```
I have no idea what to do next with this?

**Comment by thaytan** [comment]
I don't know why you'd get that error. Something related to your hand-built GStreamer - but I think know why you'd end it would install a .la file that looks for a non-existent lib-libpthread

**Comment by kevkid** [comment]
@thaytan Yeah, its weird. I built Gstreamer using cerbero and gstreamer 1.15

**Comment by tp-m** [comment]
I think this got closed by mistake, I must've typoed an issue/mr number in my commit, sorry.
